import {
  FileCode,
  ScanText,
  Wrench,
  Shield,
  Book,
  Zap,
  Lock,
  ImageUp,
  Palette,
  FilePen,
  Layers,
  Smartphone,
  FileImage,
  Scissors,
  Combine,
  PocketKnife,
  PenTool,
  Image,
} from 'lucide-react';

export const categories = [
  {
    name: 'Popular Tools',
    tools: [
      {
        href: '/merge-pdf',
        name: 'Merge PDF',
        icon: Combine,
        subtitle: 'Combine multiple PDFs into one file.',
      },
      {
        href: '/split-pdf',
        name: 'Split PDF',
        icon: Scissors,
        subtitle: 'Split PDF into multiple files.',
      },
      {
        href: '/compress-pdf',
        name: 'Compress PDF',
        icon: Scissors,
        subtitle: 'Reduce the file size of your PDF.',
      },
      {
        href: '/pdf-editor',
        name: 'PDF Editor',
        icon: PocketKnife,
        subtitle:
          'Annotate, highlight, redact, comment, add shapes/images, search, and view PDFs',
      },
      {
        href: '/sign-pdf',
        name: 'Sign PDF',
        icon: PenTool,
        subtitle: 'Draw, type, or upload your signature.',
      },
      {
        href: '/pdf-summary',
        name: 'Summary PDF',
        icon: Book,
        subtitle: 'Summarize your pdf content using AI technology.',
      },
      {
        href: '/word-count',
        name: 'Word Count PDF',
        icon: Book,
        subtitle: 'Count words in your PDF content using AI technology.',
      },
      {
        href: '/watermark-tiling',
        name: 'Watermark Tiling',
        icon: Book,
        subtitle: 'Tile watermarks across your PDF pages.',
      },
      {
        href: '/encrypt-pdf',
        name: 'Encrypt PDF',
        icon: Lock,
        subtitle: 'Lock your PDF by adding a password.',
      },
      {
        href: '/repair-pdf',
        name: 'Repair PDF',
        icon: Wrench,
        subtitle: 'Recover data from corrupted or damaged PDF files.',
      },
      {
        href: '/ocr-pdf',
        name: 'OCR PDF',
        icon: ScanText,
        subtitle: 'Make a PDF searchable and copyable.',
      },
      {
        href: '/convert-pdf/pdf-to-jpg',
        name: 'PDF to JPG',
        icon: FileImage,
        subtitle: 'Convert each PDF page into a JPG image.',
      },
      {
        href: '/convert-pdf/pdf-to-png',
        name: 'PDF to PNG',
        icon: FileImage,
        subtitle: 'Convert each PDF page into a PNG image.',
      },
      {
        href: '/convert-pdf/pdf-to-webp',
        name: 'PDF to WebP',
        icon: FileImage,
        subtitle: 'Convert each PDF page into a WebP image.',
      },
      {
        href: '/convert-pdf/pdf-to-bmp',
        name: 'PDF to BMP',
        icon: FileImage,
        subtitle: 'Convert each PDF page into a BMP image.',
      },
      {
        href: '/convert-pdf/pdf-to-tiff',
        name: 'PDF to TIFF',
        icon: FileImage,
        subtitle: 'Convert each PDF page into a TIFF image.',
      },
      {
        href: '/convert-pdf/pdf-to-greyscale',
        name: 'PDF to Greyscale',
        icon: Palette,
        subtitle: 'Convert all colors to black and white.',
      },
      {
        href: '/convert-pdf/pdf-to-json',
        name: 'PDF to JSON',
        icon: FileCode,
        subtitle: 'Convert PDF files to JSON format.',
      },
      {
        href: '/convert-pdf/image-to-pdf',
        name: 'Image to PDF',
        icon: Image,
        subtitle: 'Convert JPG, PNG, WebP, BMP, TIFF, SVG, HEIC to PDF.',
      },
      {
        href: '/convert-pdf/jpg-to-pdf',
        name: 'JPG to PDF',
        icon: ImageUp,
        subtitle: 'Create a PDF from one or more JPG images.',
      },
      {
        href: '/convert-pdf/png-to-pdf',
        name: 'PNG to PDF',
        icon: ImageUp,
        subtitle: 'Create a PDF from one or more PNG images.',
      },
      {
        href: '/convert-pdf/webp-to-pdf',
        name: 'WebP to PDF',
        icon: ImageUp,
        subtitle: 'Create a PDF from one or more WebP images.',
      },
      {
        href: '/convert-pdf/svg-to-pdf',
        name: 'SVG to PDF',
        icon: PenTool,
        subtitle: 'Create a PDF from one or more SVG images.',
      },
      {
        href: '/convert-pdf/bmp-to-pdf',
        name: 'BMP to PDF',
        icon: Image,
        subtitle: 'Create a PDF from one or more BMP images.',
      },
      {
        href: '/convert-pdf/heic-to-pdf',
        name: 'HEIC to PDF',
        icon: Smartphone,
        subtitle: 'Create a PDF from one or more HEIC images.',
      },
      {
        href: '/convert-pdf/tiff-to-pdf',
        name: 'TIFF to PDF',
        icon: Layers,
        subtitle: 'Create a PDF from one or more TIFF images.',
      },
      {
        href: '/convert-pdf/txt-to-pdf',
        name: 'Text to PDF',
        icon: FilePen,
        subtitle: 'Convert a plain text file into a PDF.',
      },
      {
        href: '/convert-pdf/json-to-pdf',
        name: 'JSON to PDF',
        icon: FileCode,
        subtitle: 'Convert JSON files to PDF format.',
      },
    ],
  },
];
